export const menuData = [
    {
        item:"fried chiken",
        category:"Populor",
        type: ["Lunch", "Dinner"],
        price: 165,
        logo:"",
        Stock: "Available",
    },
    {
        item:"fried chilli",
        category:"populor",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Not Available",
    },
    {
        item:"chiken curri",
        category:"Non Veg",
        type: ["Lunch", "Dinner"],
        price: 119,
        Stock: "Available",
    },
    {
        item:"chiken pakoda",
        category:"Non Veg",
        type: ["staters","Lunch", "Dinner"],
        price: 185,
        Stock: "Available",
    },
    {
        item:"chiken 65",
        category:"populor",
        type: ["Lunch", "Dinner"],
        price: 229,
        Stock: "Available",
    },
    {
        item:"kadhai chiken",
        category:"Non Veg",
        type: ["Lunch", "Dinner"],
        price: 285,
        Stock: "Available",
    },
    {
        item:"chiken 95",
        category:"Non Veg",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"Cheese Burger",
        category:"Burger",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"Cheese Pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"Cheese corn Pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"Extra panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"panner corn pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"panner tandoor pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"masala=panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"Cheese Pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"Cheese corn Pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"Extra panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"panner corn pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"panner tandoor pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"masala=panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"Cheese Pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"Cheese corn Pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"Extra panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"panner corn pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"panner tandoor pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"masala=panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"Cheese Pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"Cheese corn Pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"Extra panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"panner corn pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"panner tandoor pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },{
        item:"masala=panner pizza",
        category:"pizza",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"mango juice",
        category:"juice",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"Apple Pie",
        category:"juice",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    },
    {
        item:"mango sheck",
        category:"juice",
        type: ["Lunch", "Dinner"],
        price: 199,
        Stock: "Available",
    }

]